---
apiVersion: v1
kind: Service
metadata:
  name: postgresdb
  labels:
    app: postgresdb
spec:
  ports:
    - port: 5432
  selector:
    app: postgresdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  labels:
    app: postgresdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
  labels:
    app: postgresdb
spec:
  selector:
    matchLabels:
      app: postgresdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
        - image: postgres
          name: postgresdb
          env:
            - name: POSTGRES_USER
              value: matthias
            - name: POSTGRES_DB
              value: mydb
            - name: POSTGRES_PASSWORD
              value: password
          ports:
            - containerPort: 5432
              name: postgresdb
          volumeMounts:
            - name: postgresdb
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-claim